name = "FluxExtra"
uuid = "81ebe36b-92a1-4b50-bd7a-fa963d2933c8"
authors = ["Open Machine Learning Association <a_ill@outlook.com>"]
version = "0.4.1"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Flux = "0.12"
julia = "1.6"
