name = "FluxExtra"
uuid = "81ebe36b-92a1-4b50-bd7a-fa963d2933c8"
authors = ["Open Machone Learning Association <a_ill@outlook.com>"]
version = "0.2.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1.6"
